package com.taolijie.schedule.model;

import java.util.Date;

public class TaskModel {
    private Integer id;

    private Date createdTime;

    private Date updateTime;

    private Date exeAt;

    private String taskName;

    private String taskGroup;

    private String triggerName;

    private String triggerGroup;

    private String beanName;

    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.created_time
     *
     * @return the value of task.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.created_time
     *
     * @param createdTime the value for task.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param updateTime the value for task.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.exe_at
     *
     * @return the value of task.exe_at
     *
     * @mbggenerated
     */
    public Date getExeAt() {
        return exeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.exe_at
     *
     * @param exeAt the value for task.exe_at
     *
     * @mbggenerated
     */
    public void setExeAt(Date exeAt) {
        this.exeAt = exeAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_name
     *
     * @return the value of task.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_group
     *
     * @return the value of task.task_group
     *
     * @mbggenerated
     */
    public String getTaskGroup() {
        return taskGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_group
     *
     * @param taskGroup the value for task.task_group
     *
     * @mbggenerated
     */
    public void setTaskGroup(String taskGroup) {
        this.taskGroup = taskGroup == null ? null : taskGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.trigger_name
     *
     * @return the value of task.trigger_name
     *
     * @mbggenerated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.trigger_name
     *
     * @param triggerName the value for task.trigger_name
     *
     * @mbggenerated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.trigger_group
     *
     * @return the value of task.trigger_group
     *
     * @mbggenerated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.trigger_group
     *
     * @param triggerGroup the value for task.trigger_group
     *
     * @mbggenerated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.memo
     *
     * @return the value of task.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    public String getBeanName() {
        return beanName;
    }

    public void setBeanName(String beanName) {
        this.beanName = beanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.memo
     *
     * @param memo the value for task.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}