package com.taolijie.schedule.model;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class TaskModel {
    private Integer id;

    private Date createdTime;

    private Date updateTime;

    private Date exeAt;

    private String taskName;

    private String taskGroup;

    private String triggerName;

    private String triggerGroup;

    private String cronExp;

    /**
     * 接口调用地址
     */
    private String callbackPath;
    /**
     * 接口调用主机名
     */
    private String callbackHost;
    /**
     * 接口调用端口
     */
    private Integer callbackPort;

    /**
     * 接口调用方法
     */
    private String callbackMethod;

    private Integer status;

    private String parameter;

    private String memo;

    // 只查询使用
    @JSONField(serialize = false)
    private Date startTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Date getExeAt() {
        return exeAt;
    }

    public void setExeAt(Date exeAt) {
        this.exeAt = exeAt;
    }

    public String getCronExp() {
        return cronExp;
    }

    public void setCronExp(String cronExp) {
        this.cronExp = cronExp;
    }

    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_name
     *
     * @param taskName the value for task.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_group
     *
     * @return the value of task.task_group
     *
     * @mbggenerated
     */
    public String getTaskGroup() {
        return taskGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_group
     *
     * @param taskGroup the value for task.task_group
     *
     * @mbggenerated
     */
    public void setTaskGroup(String taskGroup) {
        this.taskGroup = taskGroup == null ? null : taskGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.trigger_name
     *
     * @return the value of task.trigger_name
     *
     * @mbggenerated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.trigger_name
     *
     * @param triggerName the value for task.trigger_name
     *
     * @mbggenerated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.trigger_group
     *
     * @return the value of task.trigger_group
     *
     * @mbggenerated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.trigger_group
     *
     * @param triggerGroup the value for task.trigger_group
     *
     * @mbggenerated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.memo
     *
     * @return the value of task.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    public String getCallbackPath() {
        return callbackPath;
    }

    public void setCallbackPath(String callbackPath) {
        this.callbackPath = callbackPath;
    }

    public String getCallbackHost() {
        return callbackHost;
    }

    public void setCallbackHost(String callbackHost) {
        this.callbackHost = callbackHost;
    }

    public Integer getCallbackPort() {
        return callbackPort;
    }

    public void setCallbackPort(Integer callbackPort) {
        this.callbackPort = callbackPort;
    }

    public String getParameter() {
        return parameter;
    }

    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    public String getCallbackMethod() {
        return callbackMethod;
    }

    public void setCallbackMethod(String callbackMethod) {
        this.callbackMethod = callbackMethod;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("TaskModel{");
        sb.append("id=").append(id);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", exeAt=").append(exeAt);
        sb.append(", taskName='").append(taskName).append('\'');
        sb.append(", taskGroup='").append(taskGroup).append('\'');
        sb.append(", triggerName='").append(triggerName).append('\'');
        sb.append(", triggerGroup='").append(triggerGroup).append('\'');
        sb.append(", callbackPath='").append(callbackPath).append('\'');
        sb.append(", callbackHost='").append(callbackHost).append('\'');
        sb.append(", callbackPort=").append(callbackPort);
        sb.append(", callbackMethod='").append(callbackMethod).append('\'');
        sb.append(", status=").append(status);
        sb.append(", parameter='").append(parameter).append('\'');
        sb.append(", memo='").append(memo).append('\'');
        sb.append('}');
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.memo
     *
     * @param memo the value for task.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}