package com.taolijie.schedule.dao.mapper;

import com.taolijie.schedule.model.FinishReqModel;
import org.springframework.stereotype.Repository;

@Repository
public interface FinishReqModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    int insert(FinishReqModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    int insertSelective(FinishReqModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    FinishReqModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FinishReqModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finish_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FinishReqModel record);
}