package com.taolijie.schedule.dao.mapper;

import com.taolijie.schedule.model.QuestAssignModel;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestAssignModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    int insert(QuestAssignModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    int insertSelective(QuestAssignModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    QuestAssignModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestAssignModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quest_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestAssignModel record);
}